// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package io.emqx.exhook;

public interface ClientSubscribeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v1.ClientSubscribeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.emqx.exhook.v1.ClientInfo clientinfo = 1;</code>
   * @return Whether the clientinfo field is set.
   */
  boolean hasClientinfo();
  /**
   * <code>.emqx.exhook.v1.ClientInfo clientinfo = 1;</code>
   * @return The clientinfo.
   */
  io.emqx.exhook.ClientInfo getClientinfo();
  /**
   * <code>.emqx.exhook.v1.ClientInfo clientinfo = 1;</code>
   */
  io.emqx.exhook.ClientInfoOrBuilder getClientinfoOrBuilder();

  /**
   * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
   */
  java.util.List<io.emqx.exhook.Property> 
      getPropsList();
  /**
   * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
   */
  io.emqx.exhook.Property getProps(int index);
  /**
   * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
   */
  int getPropsCount();
  /**
   * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
   */
  java.util.List<? extends io.emqx.exhook.PropertyOrBuilder> 
      getPropsOrBuilderList();
  /**
   * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
   */
  io.emqx.exhook.PropertyOrBuilder getPropsOrBuilder(
      int index);

  /**
   * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
   */
  java.util.List<io.emqx.exhook.TopicFilter> 
      getTopicFiltersList();
  /**
   * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
   */
  io.emqx.exhook.TopicFilter getTopicFilters(int index);
  /**
   * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
   */
  int getTopicFiltersCount();
  /**
   * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
   */
  java.util.List<? extends io.emqx.exhook.TopicFilterOrBuilder> 
      getTopicFiltersOrBuilderList();
  /**
   * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
   */
  io.emqx.exhook.TopicFilterOrBuilder getTopicFiltersOrBuilder(
      int index);
}
