// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package io.emqx.exhook;

/**
 * Protobuf type {@code emqx.exhook.v1.ClientUnsubscribeRequest}
 */
public final class ClientUnsubscribeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:emqx.exhook.v1.ClientUnsubscribeRequest)
    ClientUnsubscribeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientUnsubscribeRequest.newBuilder() to construct.
  private ClientUnsubscribeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientUnsubscribeRequest() {
    props_ = java.util.Collections.emptyList();
    topicFilters_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClientUnsubscribeRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientUnsubscribeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.emqx.exhook.ClientInfo.Builder subBuilder = null;
            if (clientinfo_ != null) {
              subBuilder = clientinfo_.toBuilder();
            }
            clientinfo_ = input.readMessage(io.emqx.exhook.ClientInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(clientinfo_);
              clientinfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              props_ = new java.util.ArrayList<io.emqx.exhook.Property>();
              mutable_bitField0_ |= 0x00000001;
            }
            props_.add(
                input.readMessage(io.emqx.exhook.Property.parser(), extensionRegistry));
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              topicFilters_ = new java.util.ArrayList<io.emqx.exhook.TopicFilter>();
              mutable_bitField0_ |= 0x00000002;
            }
            topicFilters_.add(
                input.readMessage(io.emqx.exhook.TopicFilter.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        props_ = java.util.Collections.unmodifiableList(props_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        topicFilters_ = java.util.Collections.unmodifiableList(topicFilters_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v1_ClientUnsubscribeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v1_ClientUnsubscribeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.emqx.exhook.ClientUnsubscribeRequest.class, io.emqx.exhook.ClientUnsubscribeRequest.Builder.class);
  }

  public static final int CLIENTINFO_FIELD_NUMBER = 1;
  private io.emqx.exhook.ClientInfo clientinfo_;
  /**
   * <code>.emqx.exhook.v1.ClientInfo clientinfo = 1;</code>
   * @return Whether the clientinfo field is set.
   */
  @java.lang.Override
  public boolean hasClientinfo() {
    return clientinfo_ != null;
  }
  /**
   * <code>.emqx.exhook.v1.ClientInfo clientinfo = 1;</code>
   * @return The clientinfo.
   */
  @java.lang.Override
  public io.emqx.exhook.ClientInfo getClientinfo() {
    return clientinfo_ == null ? io.emqx.exhook.ClientInfo.getDefaultInstance() : clientinfo_;
  }
  /**
   * <code>.emqx.exhook.v1.ClientInfo clientinfo = 1;</code>
   */
  @java.lang.Override
  public io.emqx.exhook.ClientInfoOrBuilder getClientinfoOrBuilder() {
    return getClientinfo();
  }

  public static final int PROPS_FIELD_NUMBER = 2;
  private java.util.List<io.emqx.exhook.Property> props_;
  /**
   * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
   */
  @java.lang.Override
  public java.util.List<io.emqx.exhook.Property> getPropsList() {
    return props_;
  }
  /**
   * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.emqx.exhook.PropertyOrBuilder> 
      getPropsOrBuilderList() {
    return props_;
  }
  /**
   * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
   */
  @java.lang.Override
  public int getPropsCount() {
    return props_.size();
  }
  /**
   * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
   */
  @java.lang.Override
  public io.emqx.exhook.Property getProps(int index) {
    return props_.get(index);
  }
  /**
   * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
   */
  @java.lang.Override
  public io.emqx.exhook.PropertyOrBuilder getPropsOrBuilder(
      int index) {
    return props_.get(index);
  }

  public static final int TOPIC_FILTERS_FIELD_NUMBER = 3;
  private java.util.List<io.emqx.exhook.TopicFilter> topicFilters_;
  /**
   * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
   */
  @java.lang.Override
  public java.util.List<io.emqx.exhook.TopicFilter> getTopicFiltersList() {
    return topicFilters_;
  }
  /**
   * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.emqx.exhook.TopicFilterOrBuilder> 
      getTopicFiltersOrBuilderList() {
    return topicFilters_;
  }
  /**
   * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
   */
  @java.lang.Override
  public int getTopicFiltersCount() {
    return topicFilters_.size();
  }
  /**
   * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
   */
  @java.lang.Override
  public io.emqx.exhook.TopicFilter getTopicFilters(int index) {
    return topicFilters_.get(index);
  }
  /**
   * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
   */
  @java.lang.Override
  public io.emqx.exhook.TopicFilterOrBuilder getTopicFiltersOrBuilder(
      int index) {
    return topicFilters_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (clientinfo_ != null) {
      output.writeMessage(1, getClientinfo());
    }
    for (int i = 0; i < props_.size(); i++) {
      output.writeMessage(2, props_.get(i));
    }
    for (int i = 0; i < topicFilters_.size(); i++) {
      output.writeMessage(3, topicFilters_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (clientinfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getClientinfo());
    }
    for (int i = 0; i < props_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, props_.get(i));
    }
    for (int i = 0; i < topicFilters_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, topicFilters_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.emqx.exhook.ClientUnsubscribeRequest)) {
      return super.equals(obj);
    }
    io.emqx.exhook.ClientUnsubscribeRequest other = (io.emqx.exhook.ClientUnsubscribeRequest) obj;

    if (hasClientinfo() != other.hasClientinfo()) return false;
    if (hasClientinfo()) {
      if (!getClientinfo()
          .equals(other.getClientinfo())) return false;
    }
    if (!getPropsList()
        .equals(other.getPropsList())) return false;
    if (!getTopicFiltersList()
        .equals(other.getTopicFiltersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasClientinfo()) {
      hash = (37 * hash) + CLIENTINFO_FIELD_NUMBER;
      hash = (53 * hash) + getClientinfo().hashCode();
    }
    if (getPropsCount() > 0) {
      hash = (37 * hash) + PROPS_FIELD_NUMBER;
      hash = (53 * hash) + getPropsList().hashCode();
    }
    if (getTopicFiltersCount() > 0) {
      hash = (37 * hash) + TOPIC_FILTERS_FIELD_NUMBER;
      hash = (53 * hash) + getTopicFiltersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.emqx.exhook.ClientUnsubscribeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.ClientUnsubscribeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.ClientUnsubscribeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.ClientUnsubscribeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.ClientUnsubscribeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.ClientUnsubscribeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.ClientUnsubscribeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.ClientUnsubscribeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.emqx.exhook.ClientUnsubscribeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.ClientUnsubscribeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.emqx.exhook.ClientUnsubscribeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.ClientUnsubscribeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.emqx.exhook.ClientUnsubscribeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code emqx.exhook.v1.ClientUnsubscribeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:emqx.exhook.v1.ClientUnsubscribeRequest)
      io.emqx.exhook.ClientUnsubscribeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v1_ClientUnsubscribeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v1_ClientUnsubscribeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.emqx.exhook.ClientUnsubscribeRequest.class, io.emqx.exhook.ClientUnsubscribeRequest.Builder.class);
    }

    // Construct using io.emqx.exhook.ClientUnsubscribeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPropsFieldBuilder();
        getTopicFiltersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (clientinfoBuilder_ == null) {
        clientinfo_ = null;
      } else {
        clientinfo_ = null;
        clientinfoBuilder_ = null;
      }
      if (propsBuilder_ == null) {
        props_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        propsBuilder_.clear();
      }
      if (topicFiltersBuilder_ == null) {
        topicFilters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        topicFiltersBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v1_ClientUnsubscribeRequest_descriptor;
    }

    @java.lang.Override
    public io.emqx.exhook.ClientUnsubscribeRequest getDefaultInstanceForType() {
      return io.emqx.exhook.ClientUnsubscribeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.emqx.exhook.ClientUnsubscribeRequest build() {
      io.emqx.exhook.ClientUnsubscribeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.emqx.exhook.ClientUnsubscribeRequest buildPartial() {
      io.emqx.exhook.ClientUnsubscribeRequest result = new io.emqx.exhook.ClientUnsubscribeRequest(this);
      int from_bitField0_ = bitField0_;
      if (clientinfoBuilder_ == null) {
        result.clientinfo_ = clientinfo_;
      } else {
        result.clientinfo_ = clientinfoBuilder_.build();
      }
      if (propsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          props_ = java.util.Collections.unmodifiableList(props_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.props_ = props_;
      } else {
        result.props_ = propsBuilder_.build();
      }
      if (topicFiltersBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          topicFilters_ = java.util.Collections.unmodifiableList(topicFilters_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.topicFilters_ = topicFilters_;
      } else {
        result.topicFilters_ = topicFiltersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.emqx.exhook.ClientUnsubscribeRequest) {
        return mergeFrom((io.emqx.exhook.ClientUnsubscribeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.emqx.exhook.ClientUnsubscribeRequest other) {
      if (other == io.emqx.exhook.ClientUnsubscribeRequest.getDefaultInstance()) return this;
      if (other.hasClientinfo()) {
        mergeClientinfo(other.getClientinfo());
      }
      if (propsBuilder_ == null) {
        if (!other.props_.isEmpty()) {
          if (props_.isEmpty()) {
            props_ = other.props_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePropsIsMutable();
            props_.addAll(other.props_);
          }
          onChanged();
        }
      } else {
        if (!other.props_.isEmpty()) {
          if (propsBuilder_.isEmpty()) {
            propsBuilder_.dispose();
            propsBuilder_ = null;
            props_ = other.props_;
            bitField0_ = (bitField0_ & ~0x00000001);
            propsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPropsFieldBuilder() : null;
          } else {
            propsBuilder_.addAllMessages(other.props_);
          }
        }
      }
      if (topicFiltersBuilder_ == null) {
        if (!other.topicFilters_.isEmpty()) {
          if (topicFilters_.isEmpty()) {
            topicFilters_ = other.topicFilters_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTopicFiltersIsMutable();
            topicFilters_.addAll(other.topicFilters_);
          }
          onChanged();
        }
      } else {
        if (!other.topicFilters_.isEmpty()) {
          if (topicFiltersBuilder_.isEmpty()) {
            topicFiltersBuilder_.dispose();
            topicFiltersBuilder_ = null;
            topicFilters_ = other.topicFilters_;
            bitField0_ = (bitField0_ & ~0x00000002);
            topicFiltersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTopicFiltersFieldBuilder() : null;
          } else {
            topicFiltersBuilder_.addAllMessages(other.topicFilters_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.emqx.exhook.ClientUnsubscribeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.emqx.exhook.ClientUnsubscribeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private io.emqx.exhook.ClientInfo clientinfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.emqx.exhook.ClientInfo, io.emqx.exhook.ClientInfo.Builder, io.emqx.exhook.ClientInfoOrBuilder> clientinfoBuilder_;
    /**
     * <code>.emqx.exhook.v1.ClientInfo clientinfo = 1;</code>
     * @return Whether the clientinfo field is set.
     */
    public boolean hasClientinfo() {
      return clientinfoBuilder_ != null || clientinfo_ != null;
    }
    /**
     * <code>.emqx.exhook.v1.ClientInfo clientinfo = 1;</code>
     * @return The clientinfo.
     */
    public io.emqx.exhook.ClientInfo getClientinfo() {
      if (clientinfoBuilder_ == null) {
        return clientinfo_ == null ? io.emqx.exhook.ClientInfo.getDefaultInstance() : clientinfo_;
      } else {
        return clientinfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.emqx.exhook.v1.ClientInfo clientinfo = 1;</code>
     */
    public Builder setClientinfo(io.emqx.exhook.ClientInfo value) {
      if (clientinfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        clientinfo_ = value;
        onChanged();
      } else {
        clientinfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v1.ClientInfo clientinfo = 1;</code>
     */
    public Builder setClientinfo(
        io.emqx.exhook.ClientInfo.Builder builderForValue) {
      if (clientinfoBuilder_ == null) {
        clientinfo_ = builderForValue.build();
        onChanged();
      } else {
        clientinfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v1.ClientInfo clientinfo = 1;</code>
     */
    public Builder mergeClientinfo(io.emqx.exhook.ClientInfo value) {
      if (clientinfoBuilder_ == null) {
        if (clientinfo_ != null) {
          clientinfo_ =
            io.emqx.exhook.ClientInfo.newBuilder(clientinfo_).mergeFrom(value).buildPartial();
        } else {
          clientinfo_ = value;
        }
        onChanged();
      } else {
        clientinfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v1.ClientInfo clientinfo = 1;</code>
     */
    public Builder clearClientinfo() {
      if (clientinfoBuilder_ == null) {
        clientinfo_ = null;
        onChanged();
      } else {
        clientinfo_ = null;
        clientinfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.emqx.exhook.v1.ClientInfo clientinfo = 1;</code>
     */
    public io.emqx.exhook.ClientInfo.Builder getClientinfoBuilder() {
      
      onChanged();
      return getClientinfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.emqx.exhook.v1.ClientInfo clientinfo = 1;</code>
     */
    public io.emqx.exhook.ClientInfoOrBuilder getClientinfoOrBuilder() {
      if (clientinfoBuilder_ != null) {
        return clientinfoBuilder_.getMessageOrBuilder();
      } else {
        return clientinfo_ == null ?
            io.emqx.exhook.ClientInfo.getDefaultInstance() : clientinfo_;
      }
    }
    /**
     * <code>.emqx.exhook.v1.ClientInfo clientinfo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.emqx.exhook.ClientInfo, io.emqx.exhook.ClientInfo.Builder, io.emqx.exhook.ClientInfoOrBuilder> 
        getClientinfoFieldBuilder() {
      if (clientinfoBuilder_ == null) {
        clientinfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.emqx.exhook.ClientInfo, io.emqx.exhook.ClientInfo.Builder, io.emqx.exhook.ClientInfoOrBuilder>(
                getClientinfo(),
                getParentForChildren(),
                isClean());
        clientinfo_ = null;
      }
      return clientinfoBuilder_;
    }

    private java.util.List<io.emqx.exhook.Property> props_ =
      java.util.Collections.emptyList();
    private void ensurePropsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        props_ = new java.util.ArrayList<io.emqx.exhook.Property>(props_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.emqx.exhook.Property, io.emqx.exhook.Property.Builder, io.emqx.exhook.PropertyOrBuilder> propsBuilder_;

    /**
     * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
     */
    public java.util.List<io.emqx.exhook.Property> getPropsList() {
      if (propsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(props_);
      } else {
        return propsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
     */
    public int getPropsCount() {
      if (propsBuilder_ == null) {
        return props_.size();
      } else {
        return propsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
     */
    public io.emqx.exhook.Property getProps(int index) {
      if (propsBuilder_ == null) {
        return props_.get(index);
      } else {
        return propsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
     */
    public Builder setProps(
        int index, io.emqx.exhook.Property value) {
      if (propsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropsIsMutable();
        props_.set(index, value);
        onChanged();
      } else {
        propsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
     */
    public Builder setProps(
        int index, io.emqx.exhook.Property.Builder builderForValue) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        props_.set(index, builderForValue.build());
        onChanged();
      } else {
        propsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
     */
    public Builder addProps(io.emqx.exhook.Property value) {
      if (propsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropsIsMutable();
        props_.add(value);
        onChanged();
      } else {
        propsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
     */
    public Builder addProps(
        int index, io.emqx.exhook.Property value) {
      if (propsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePropsIsMutable();
        props_.add(index, value);
        onChanged();
      } else {
        propsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
     */
    public Builder addProps(
        io.emqx.exhook.Property.Builder builderForValue) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        props_.add(builderForValue.build());
        onChanged();
      } else {
        propsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
     */
    public Builder addProps(
        int index, io.emqx.exhook.Property.Builder builderForValue) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        props_.add(index, builderForValue.build());
        onChanged();
      } else {
        propsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
     */
    public Builder addAllProps(
        java.lang.Iterable<? extends io.emqx.exhook.Property> values) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, props_);
        onChanged();
      } else {
        propsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
     */
    public Builder clearProps() {
      if (propsBuilder_ == null) {
        props_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        propsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
     */
    public Builder removeProps(int index) {
      if (propsBuilder_ == null) {
        ensurePropsIsMutable();
        props_.remove(index);
        onChanged();
      } else {
        propsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
     */
    public io.emqx.exhook.Property.Builder getPropsBuilder(
        int index) {
      return getPropsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
     */
    public io.emqx.exhook.PropertyOrBuilder getPropsOrBuilder(
        int index) {
      if (propsBuilder_ == null) {
        return props_.get(index);  } else {
        return propsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
     */
    public java.util.List<? extends io.emqx.exhook.PropertyOrBuilder> 
         getPropsOrBuilderList() {
      if (propsBuilder_ != null) {
        return propsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(props_);
      }
    }
    /**
     * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
     */
    public io.emqx.exhook.Property.Builder addPropsBuilder() {
      return getPropsFieldBuilder().addBuilder(
          io.emqx.exhook.Property.getDefaultInstance());
    }
    /**
     * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
     */
    public io.emqx.exhook.Property.Builder addPropsBuilder(
        int index) {
      return getPropsFieldBuilder().addBuilder(
          index, io.emqx.exhook.Property.getDefaultInstance());
    }
    /**
     * <code>repeated .emqx.exhook.v1.Property props = 2;</code>
     */
    public java.util.List<io.emqx.exhook.Property.Builder> 
         getPropsBuilderList() {
      return getPropsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.emqx.exhook.Property, io.emqx.exhook.Property.Builder, io.emqx.exhook.PropertyOrBuilder> 
        getPropsFieldBuilder() {
      if (propsBuilder_ == null) {
        propsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.emqx.exhook.Property, io.emqx.exhook.Property.Builder, io.emqx.exhook.PropertyOrBuilder>(
                props_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        props_ = null;
      }
      return propsBuilder_;
    }

    private java.util.List<io.emqx.exhook.TopicFilter> topicFilters_ =
      java.util.Collections.emptyList();
    private void ensureTopicFiltersIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        topicFilters_ = new java.util.ArrayList<io.emqx.exhook.TopicFilter>(topicFilters_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.emqx.exhook.TopicFilter, io.emqx.exhook.TopicFilter.Builder, io.emqx.exhook.TopicFilterOrBuilder> topicFiltersBuilder_;

    /**
     * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
     */
    public java.util.List<io.emqx.exhook.TopicFilter> getTopicFiltersList() {
      if (topicFiltersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(topicFilters_);
      } else {
        return topicFiltersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
     */
    public int getTopicFiltersCount() {
      if (topicFiltersBuilder_ == null) {
        return topicFilters_.size();
      } else {
        return topicFiltersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
     */
    public io.emqx.exhook.TopicFilter getTopicFilters(int index) {
      if (topicFiltersBuilder_ == null) {
        return topicFilters_.get(index);
      } else {
        return topicFiltersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
     */
    public Builder setTopicFilters(
        int index, io.emqx.exhook.TopicFilter value) {
      if (topicFiltersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTopicFiltersIsMutable();
        topicFilters_.set(index, value);
        onChanged();
      } else {
        topicFiltersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
     */
    public Builder setTopicFilters(
        int index, io.emqx.exhook.TopicFilter.Builder builderForValue) {
      if (topicFiltersBuilder_ == null) {
        ensureTopicFiltersIsMutable();
        topicFilters_.set(index, builderForValue.build());
        onChanged();
      } else {
        topicFiltersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
     */
    public Builder addTopicFilters(io.emqx.exhook.TopicFilter value) {
      if (topicFiltersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTopicFiltersIsMutable();
        topicFilters_.add(value);
        onChanged();
      } else {
        topicFiltersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
     */
    public Builder addTopicFilters(
        int index, io.emqx.exhook.TopicFilter value) {
      if (topicFiltersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTopicFiltersIsMutable();
        topicFilters_.add(index, value);
        onChanged();
      } else {
        topicFiltersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
     */
    public Builder addTopicFilters(
        io.emqx.exhook.TopicFilter.Builder builderForValue) {
      if (topicFiltersBuilder_ == null) {
        ensureTopicFiltersIsMutable();
        topicFilters_.add(builderForValue.build());
        onChanged();
      } else {
        topicFiltersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
     */
    public Builder addTopicFilters(
        int index, io.emqx.exhook.TopicFilter.Builder builderForValue) {
      if (topicFiltersBuilder_ == null) {
        ensureTopicFiltersIsMutable();
        topicFilters_.add(index, builderForValue.build());
        onChanged();
      } else {
        topicFiltersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
     */
    public Builder addAllTopicFilters(
        java.lang.Iterable<? extends io.emqx.exhook.TopicFilter> values) {
      if (topicFiltersBuilder_ == null) {
        ensureTopicFiltersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, topicFilters_);
        onChanged();
      } else {
        topicFiltersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
     */
    public Builder clearTopicFilters() {
      if (topicFiltersBuilder_ == null) {
        topicFilters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        topicFiltersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
     */
    public Builder removeTopicFilters(int index) {
      if (topicFiltersBuilder_ == null) {
        ensureTopicFiltersIsMutable();
        topicFilters_.remove(index);
        onChanged();
      } else {
        topicFiltersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
     */
    public io.emqx.exhook.TopicFilter.Builder getTopicFiltersBuilder(
        int index) {
      return getTopicFiltersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
     */
    public io.emqx.exhook.TopicFilterOrBuilder getTopicFiltersOrBuilder(
        int index) {
      if (topicFiltersBuilder_ == null) {
        return topicFilters_.get(index);  } else {
        return topicFiltersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
     */
    public java.util.List<? extends io.emqx.exhook.TopicFilterOrBuilder> 
         getTopicFiltersOrBuilderList() {
      if (topicFiltersBuilder_ != null) {
        return topicFiltersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(topicFilters_);
      }
    }
    /**
     * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
     */
    public io.emqx.exhook.TopicFilter.Builder addTopicFiltersBuilder() {
      return getTopicFiltersFieldBuilder().addBuilder(
          io.emqx.exhook.TopicFilter.getDefaultInstance());
    }
    /**
     * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
     */
    public io.emqx.exhook.TopicFilter.Builder addTopicFiltersBuilder(
        int index) {
      return getTopicFiltersFieldBuilder().addBuilder(
          index, io.emqx.exhook.TopicFilter.getDefaultInstance());
    }
    /**
     * <code>repeated .emqx.exhook.v1.TopicFilter topic_filters = 3;</code>
     */
    public java.util.List<io.emqx.exhook.TopicFilter.Builder> 
         getTopicFiltersBuilderList() {
      return getTopicFiltersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.emqx.exhook.TopicFilter, io.emqx.exhook.TopicFilter.Builder, io.emqx.exhook.TopicFilterOrBuilder> 
        getTopicFiltersFieldBuilder() {
      if (topicFiltersBuilder_ == null) {
        topicFiltersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.emqx.exhook.TopicFilter, io.emqx.exhook.TopicFilter.Builder, io.emqx.exhook.TopicFilterOrBuilder>(
                topicFilters_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        topicFilters_ = null;
      }
      return topicFiltersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:emqx.exhook.v1.ClientUnsubscribeRequest)
  }

  // @@protoc_insertion_point(class_scope:emqx.exhook.v1.ClientUnsubscribeRequest)
  private static final io.emqx.exhook.ClientUnsubscribeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.emqx.exhook.ClientUnsubscribeRequest();
  }

  public static io.emqx.exhook.ClientUnsubscribeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientUnsubscribeRequest>
      PARSER = new com.google.protobuf.AbstractParser<ClientUnsubscribeRequest>() {
    @java.lang.Override
    public ClientUnsubscribeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientUnsubscribeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientUnsubscribeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientUnsubscribeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.emqx.exhook.ClientUnsubscribeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

