// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package io.emqx.exhook;

public interface ClientInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v1.ClientInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string node = 1;</code>
   * @return The node.
   */
  java.lang.String getNode();
  /**
   * <code>string node = 1;</code>
   * @return The bytes for node.
   */
  com.google.protobuf.ByteString
      getNodeBytes();

  /**
   * <code>string clientid = 2;</code>
   * @return The clientid.
   */
  java.lang.String getClientid();
  /**
   * <code>string clientid = 2;</code>
   * @return The bytes for clientid.
   */
  com.google.protobuf.ByteString
      getClientidBytes();

  /**
   * <code>string username = 3;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 3;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 4;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 4;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string peerhost = 5;</code>
   * @return The peerhost.
   */
  java.lang.String getPeerhost();
  /**
   * <code>string peerhost = 5;</code>
   * @return The bytes for peerhost.
   */
  com.google.protobuf.ByteString
      getPeerhostBytes();

  /**
   * <code>uint32 sockport = 6;</code>
   * @return The sockport.
   */
  int getSockport();

  /**
   * <code>string protocol = 7;</code>
   * @return The protocol.
   */
  java.lang.String getProtocol();
  /**
   * <code>string protocol = 7;</code>
   * @return The bytes for protocol.
   */
  com.google.protobuf.ByteString
      getProtocolBytes();

  /**
   * <code>string mountpoint = 8;</code>
   * @return The mountpoint.
   */
  java.lang.String getMountpoint();
  /**
   * <code>string mountpoint = 8;</code>
   * @return The bytes for mountpoint.
   */
  com.google.protobuf.ByteString
      getMountpointBytes();

  /**
   * <code>bool is_superuser = 9;</code>
   * @return The isSuperuser.
   */
  boolean getIsSuperuser();

  /**
   * <code>bool anonymous = 10;</code>
   * @return The anonymous.
   */
  boolean getAnonymous();
}
