// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package io.emqx.exhook;

public interface EmptySuccessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v1.EmptySuccess)
    com.google.protobuf.MessageOrBuilder {
}
