// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package io.emqx.exhook;

public interface HookSpecOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v1.HookSpec)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The registered hooks name
   * Available value:
   *   "client.connect",      "client.connack"
   *   "client.connected",    "client.disconnected"
   *   "client.authenticate", "client.check_acl"
   *   "client.subscribe",    "client.unsubscribe"
   *   "session.created",      "session.subscribed"
   *   "session.unsubscribed", "session.resumed"
   *   "session.discarded",    "session.takeovered"
   *   "session.terminated"
   *   "message.publish", "message.delivered"
   *   "message.acked",   "message.dropped"
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * The registered hooks name
   * Available value:
   *   "client.connect",      "client.connack"
   *   "client.connected",    "client.disconnected"
   *   "client.authenticate", "client.check_acl"
   *   "client.subscribe",    "client.unsubscribe"
   *   "session.created",      "session.subscribed"
   *   "session.unsubscribed", "session.resumed"
   *   "session.discarded",    "session.takeovered"
   *   "session.terminated"
   *   "message.publish", "message.delivered"
   *   "message.acked",   "message.dropped"
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * The topic filters for message hooks
   * </pre>
   *
   * <code>repeated string topics = 2;</code>
   * @return A list containing the topics.
   */
  java.util.List<java.lang.String>
      getTopicsList();
  /**
   * <pre>
   * The topic filters for message hooks
   * </pre>
   *
   * <code>repeated string topics = 2;</code>
   * @return The count of topics.
   */
  int getTopicsCount();
  /**
   * <pre>
   * The topic filters for message hooks
   * </pre>
   *
   * <code>repeated string topics = 2;</code>
   * @param index The index of the element to return.
   * @return The topics at the given index.
   */
  java.lang.String getTopics(int index);
  /**
   * <pre>
   * The topic filters for message hooks
   * </pre>
   *
   * <code>repeated string topics = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the topics at the given index.
   */
  com.google.protobuf.ByteString
      getTopicsBytes(int index);
}
