// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package io.emqx.exhook;

public interface LoadedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v1.LoadedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .emqx.exhook.v1.HookSpec hooks = 1;</code>
   */
  java.util.List<io.emqx.exhook.HookSpec> 
      getHooksList();
  /**
   * <code>repeated .emqx.exhook.v1.HookSpec hooks = 1;</code>
   */
  io.emqx.exhook.HookSpec getHooks(int index);
  /**
   * <code>repeated .emqx.exhook.v1.HookSpec hooks = 1;</code>
   */
  int getHooksCount();
  /**
   * <code>repeated .emqx.exhook.v1.HookSpec hooks = 1;</code>
   */
  java.util.List<? extends io.emqx.exhook.HookSpecOrBuilder> 
      getHooksOrBuilderList();
  /**
   * <code>repeated .emqx.exhook.v1.HookSpec hooks = 1;</code>
   */
  io.emqx.exhook.HookSpecOrBuilder getHooksOrBuilder(
      int index);
}
