// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package io.emqx.exhook;

public interface ProviderLoadedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:emqx.exhook.v1.ProviderLoadedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.emqx.exhook.v1.BrokerInfo broker = 1;</code>
   * @return Whether the broker field is set.
   */
  boolean hasBroker();
  /**
   * <code>.emqx.exhook.v1.BrokerInfo broker = 1;</code>
   * @return The broker.
   */
  io.emqx.exhook.BrokerInfo getBroker();
  /**
   * <code>.emqx.exhook.v1.BrokerInfo broker = 1;</code>
   */
  io.emqx.exhook.BrokerInfoOrBuilder getBrokerOrBuilder();
}
