// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exhook.proto

package io.emqx.exhook;

/**
 * Protobuf type {@code emqx.exhook.v1.ValuedResponse}
 */
public final class ValuedResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:emqx.exhook.v1.ValuedResponse)
    ValuedResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ValuedResponse.newBuilder() to construct.
  private ValuedResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ValuedResponse() {
    type_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ValuedResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ValuedResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 24: {
            valueCase_ = 3;
            value_ = input.readBool();
            break;
          }
          case 34: {
            io.emqx.exhook.Message.Builder subBuilder = null;
            if (valueCase_ == 4) {
              subBuilder = ((io.emqx.exhook.Message) value_).toBuilder();
            }
            value_ =
                input.readMessage(io.emqx.exhook.Message.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.emqx.exhook.Message) value_);
              value_ = subBuilder.buildPartial();
            }
            valueCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v1_ValuedResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v1_ValuedResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.emqx.exhook.ValuedResponse.class, io.emqx.exhook.ValuedResponse.Builder.class);
  }

  /**
   * <pre>
   * The responsed value type
   *  - ignore: Ignore the responsed value
   *  - contiune: Use the responsed value and execute the next hook
   *  - stop_and_return: Use the responsed value and stop the chain executing
   * </pre>
   *
   * Protobuf enum {@code emqx.exhook.v1.ValuedResponse.ResponsedType}
   */
  public enum ResponsedType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>IGNORE = 0;</code>
     */
    IGNORE(0),
    /**
     * <code>CONTINUE = 1;</code>
     */
    CONTINUE(1),
    /**
     * <code>STOP_AND_RETURN = 2;</code>
     */
    STOP_AND_RETURN(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>IGNORE = 0;</code>
     */
    public static final int IGNORE_VALUE = 0;
    /**
     * <code>CONTINUE = 1;</code>
     */
    public static final int CONTINUE_VALUE = 1;
    /**
     * <code>STOP_AND_RETURN = 2;</code>
     */
    public static final int STOP_AND_RETURN_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponsedType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ResponsedType forNumber(int value) {
      switch (value) {
        case 0: return IGNORE;
        case 1: return CONTINUE;
        case 2: return STOP_AND_RETURN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResponsedType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResponsedType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponsedType>() {
            public ResponsedType findValueByNumber(int number) {
              return ResponsedType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.emqx.exhook.ValuedResponse.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResponsedType[] VALUES = values();

    public static ResponsedType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResponsedType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:emqx.exhook.v1.ValuedResponse.ResponsedType)
  }

  private int valueCase_ = 0;
  private java.lang.Object value_;
  public enum ValueCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    BOOL_RESULT(3),
    MESSAGE(4),
    VALUE_NOT_SET(0);
    private final int value;
    private ValueCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueCase forNumber(int value) {
      switch (value) {
        case 3: return BOOL_RESULT;
        case 4: return MESSAGE;
        case 0: return VALUE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ValueCase
  getValueCase() {
    return ValueCase.forNumber(
        valueCase_);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>.emqx.exhook.v1.ValuedResponse.ResponsedType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.emqx.exhook.v1.ValuedResponse.ResponsedType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public io.emqx.exhook.ValuedResponse.ResponsedType getType() {
    @SuppressWarnings("deprecation")
    io.emqx.exhook.ValuedResponse.ResponsedType result = io.emqx.exhook.ValuedResponse.ResponsedType.valueOf(type_);
    return result == null ? io.emqx.exhook.ValuedResponse.ResponsedType.UNRECOGNIZED : result;
  }

  public static final int BOOL_RESULT_FIELD_NUMBER = 3;
  /**
   * <pre>
   * Boolean result, used on the 'client.authenticate', 'client.check_acl' hooks
   * </pre>
   *
   * <code>bool bool_result = 3;</code>
   * @return The boolResult.
   */
  @java.lang.Override
  public boolean getBoolResult() {
    if (valueCase_ == 3) {
      return (java.lang.Boolean) value_;
    }
    return false;
  }

  public static final int MESSAGE_FIELD_NUMBER = 4;
  /**
   * <pre>
   * Message result, used on the 'message.*' hooks
   * </pre>
   *
   * <code>.emqx.exhook.v1.Message message = 4;</code>
   * @return Whether the message field is set.
   */
  @java.lang.Override
  public boolean hasMessage() {
    return valueCase_ == 4;
  }
  /**
   * <pre>
   * Message result, used on the 'message.*' hooks
   * </pre>
   *
   * <code>.emqx.exhook.v1.Message message = 4;</code>
   * @return The message.
   */
  @java.lang.Override
  public io.emqx.exhook.Message getMessage() {
    if (valueCase_ == 4) {
       return (io.emqx.exhook.Message) value_;
    }
    return io.emqx.exhook.Message.getDefaultInstance();
  }
  /**
   * <pre>
   * Message result, used on the 'message.*' hooks
   * </pre>
   *
   * <code>.emqx.exhook.v1.Message message = 4;</code>
   */
  @java.lang.Override
  public io.emqx.exhook.MessageOrBuilder getMessageOrBuilder() {
    if (valueCase_ == 4) {
       return (io.emqx.exhook.Message) value_;
    }
    return io.emqx.exhook.Message.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != io.emqx.exhook.ValuedResponse.ResponsedType.IGNORE.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (valueCase_ == 3) {
      output.writeBool(
          3, (boolean)((java.lang.Boolean) value_));
    }
    if (valueCase_ == 4) {
      output.writeMessage(4, (io.emqx.exhook.Message) value_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != io.emqx.exhook.ValuedResponse.ResponsedType.IGNORE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (valueCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            3, (boolean)((java.lang.Boolean) value_));
    }
    if (valueCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (io.emqx.exhook.Message) value_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.emqx.exhook.ValuedResponse)) {
      return super.equals(obj);
    }
    io.emqx.exhook.ValuedResponse other = (io.emqx.exhook.ValuedResponse) obj;

    if (type_ != other.type_) return false;
    if (!getValueCase().equals(other.getValueCase())) return false;
    switch (valueCase_) {
      case 3:
        if (getBoolResult()
            != other.getBoolResult()) return false;
        break;
      case 4:
        if (!getMessage()
            .equals(other.getMessage())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    switch (valueCase_) {
      case 3:
        hash = (37 * hash) + BOOL_RESULT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getBoolResult());
        break;
      case 4:
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.emqx.exhook.ValuedResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.ValuedResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.ValuedResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.ValuedResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.ValuedResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.emqx.exhook.ValuedResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.emqx.exhook.ValuedResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.ValuedResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.emqx.exhook.ValuedResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.ValuedResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.emqx.exhook.ValuedResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.emqx.exhook.ValuedResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.emqx.exhook.ValuedResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code emqx.exhook.v1.ValuedResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:emqx.exhook.v1.ValuedResponse)
      io.emqx.exhook.ValuedResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v1_ValuedResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v1_ValuedResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.emqx.exhook.ValuedResponse.class, io.emqx.exhook.ValuedResponse.Builder.class);
    }

    // Construct using io.emqx.exhook.ValuedResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = 0;

      valueCase_ = 0;
      value_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.emqx.exhook.EmqxExHookProto.internal_static_emqx_exhook_v1_ValuedResponse_descriptor;
    }

    @java.lang.Override
    public io.emqx.exhook.ValuedResponse getDefaultInstanceForType() {
      return io.emqx.exhook.ValuedResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.emqx.exhook.ValuedResponse build() {
      io.emqx.exhook.ValuedResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.emqx.exhook.ValuedResponse buildPartial() {
      io.emqx.exhook.ValuedResponse result = new io.emqx.exhook.ValuedResponse(this);
      result.type_ = type_;
      if (valueCase_ == 3) {
        result.value_ = value_;
      }
      if (valueCase_ == 4) {
        if (messageBuilder_ == null) {
          result.value_ = value_;
        } else {
          result.value_ = messageBuilder_.build();
        }
      }
      result.valueCase_ = valueCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.emqx.exhook.ValuedResponse) {
        return mergeFrom((io.emqx.exhook.ValuedResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.emqx.exhook.ValuedResponse other) {
      if (other == io.emqx.exhook.ValuedResponse.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      switch (other.getValueCase()) {
        case BOOL_RESULT: {
          setBoolResult(other.getBoolResult());
          break;
        }
        case MESSAGE: {
          mergeMessage(other.getMessage());
          break;
        }
        case VALUE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.emqx.exhook.ValuedResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.emqx.exhook.ValuedResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int valueCase_ = 0;
    private java.lang.Object value_;
    public ValueCase
        getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public Builder clearValue() {
      valueCase_ = 0;
      value_ = null;
      onChanged();
      return this;
    }


    private int type_ = 0;
    /**
     * <code>.emqx.exhook.v1.ValuedResponse.ResponsedType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.emqx.exhook.v1.ValuedResponse.ResponsedType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.emqx.exhook.v1.ValuedResponse.ResponsedType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public io.emqx.exhook.ValuedResponse.ResponsedType getType() {
      @SuppressWarnings("deprecation")
      io.emqx.exhook.ValuedResponse.ResponsedType result = io.emqx.exhook.ValuedResponse.ResponsedType.valueOf(type_);
      return result == null ? io.emqx.exhook.ValuedResponse.ResponsedType.UNRECOGNIZED : result;
    }
    /**
     * <code>.emqx.exhook.v1.ValuedResponse.ResponsedType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(io.emqx.exhook.ValuedResponse.ResponsedType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.emqx.exhook.v1.ValuedResponse.ResponsedType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * Boolean result, used on the 'client.authenticate', 'client.check_acl' hooks
     * </pre>
     *
     * <code>bool bool_result = 3;</code>
     * @return The boolResult.
     */
    public boolean getBoolResult() {
      if (valueCase_ == 3) {
        return (java.lang.Boolean) value_;
      }
      return false;
    }
    /**
     * <pre>
     * Boolean result, used on the 'client.authenticate', 'client.check_acl' hooks
     * </pre>
     *
     * <code>bool bool_result = 3;</code>
     * @param value The boolResult to set.
     * @return This builder for chaining.
     */
    public Builder setBoolResult(boolean value) {
      valueCase_ = 3;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Boolean result, used on the 'client.authenticate', 'client.check_acl' hooks
     * </pre>
     *
     * <code>bool bool_result = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBoolResult() {
      if (valueCase_ == 3) {
        valueCase_ = 0;
        value_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.emqx.exhook.Message, io.emqx.exhook.Message.Builder, io.emqx.exhook.MessageOrBuilder> messageBuilder_;
    /**
     * <pre>
     * Message result, used on the 'message.*' hooks
     * </pre>
     *
     * <code>.emqx.exhook.v1.Message message = 4;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return valueCase_ == 4;
    }
    /**
     * <pre>
     * Message result, used on the 'message.*' hooks
     * </pre>
     *
     * <code>.emqx.exhook.v1.Message message = 4;</code>
     * @return The message.
     */
    @java.lang.Override
    public io.emqx.exhook.Message getMessage() {
      if (messageBuilder_ == null) {
        if (valueCase_ == 4) {
          return (io.emqx.exhook.Message) value_;
        }
        return io.emqx.exhook.Message.getDefaultInstance();
      } else {
        if (valueCase_ == 4) {
          return messageBuilder_.getMessage();
        }
        return io.emqx.exhook.Message.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Message result, used on the 'message.*' hooks
     * </pre>
     *
     * <code>.emqx.exhook.v1.Message message = 4;</code>
     */
    public Builder setMessage(io.emqx.exhook.Message value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        messageBuilder_.setMessage(value);
      }
      valueCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * Message result, used on the 'message.*' hooks
     * </pre>
     *
     * <code>.emqx.exhook.v1.Message message = 4;</code>
     */
    public Builder setMessage(
        io.emqx.exhook.Message.Builder builderForValue) {
      if (messageBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        messageBuilder_.setMessage(builderForValue.build());
      }
      valueCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * Message result, used on the 'message.*' hooks
     * </pre>
     *
     * <code>.emqx.exhook.v1.Message message = 4;</code>
     */
    public Builder mergeMessage(io.emqx.exhook.Message value) {
      if (messageBuilder_ == null) {
        if (valueCase_ == 4 &&
            value_ != io.emqx.exhook.Message.getDefaultInstance()) {
          value_ = io.emqx.exhook.Message.newBuilder((io.emqx.exhook.Message) value_)
              .mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        if (valueCase_ == 4) {
          messageBuilder_.mergeFrom(value);
        }
        messageBuilder_.setMessage(value);
      }
      valueCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * Message result, used on the 'message.*' hooks
     * </pre>
     *
     * <code>.emqx.exhook.v1.Message message = 4;</code>
     */
    public Builder clearMessage() {
      if (messageBuilder_ == null) {
        if (valueCase_ == 4) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
      } else {
        if (valueCase_ == 4) {
          valueCase_ = 0;
          value_ = null;
        }
        messageBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Message result, used on the 'message.*' hooks
     * </pre>
     *
     * <code>.emqx.exhook.v1.Message message = 4;</code>
     */
    public io.emqx.exhook.Message.Builder getMessageBuilder() {
      return getMessageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Message result, used on the 'message.*' hooks
     * </pre>
     *
     * <code>.emqx.exhook.v1.Message message = 4;</code>
     */
    @java.lang.Override
    public io.emqx.exhook.MessageOrBuilder getMessageOrBuilder() {
      if ((valueCase_ == 4) && (messageBuilder_ != null)) {
        return messageBuilder_.getMessageOrBuilder();
      } else {
        if (valueCase_ == 4) {
          return (io.emqx.exhook.Message) value_;
        }
        return io.emqx.exhook.Message.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Message result, used on the 'message.*' hooks
     * </pre>
     *
     * <code>.emqx.exhook.v1.Message message = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.emqx.exhook.Message, io.emqx.exhook.Message.Builder, io.emqx.exhook.MessageOrBuilder> 
        getMessageFieldBuilder() {
      if (messageBuilder_ == null) {
        if (!(valueCase_ == 4)) {
          value_ = io.emqx.exhook.Message.getDefaultInstance();
        }
        messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.emqx.exhook.Message, io.emqx.exhook.Message.Builder, io.emqx.exhook.MessageOrBuilder>(
                (io.emqx.exhook.Message) value_,
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      valueCase_ = 4;
      onChanged();;
      return messageBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:emqx.exhook.v1.ValuedResponse)
  }

  // @@protoc_insertion_point(class_scope:emqx.exhook.v1.ValuedResponse)
  private static final io.emqx.exhook.ValuedResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.emqx.exhook.ValuedResponse();
  }

  public static io.emqx.exhook.ValuedResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ValuedResponse>
      PARSER = new com.google.protobuf.AbstractParser<ValuedResponse>() {
    @java.lang.Override
    public ValuedResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ValuedResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ValuedResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ValuedResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.emqx.exhook.ValuedResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

